### ISSUE TITLE
Add Chainer in DeepLearningZeroToAll?

### ISSUE THREAD

**Issue by hunkim** [surfertas/chainer-tutorials#1]
@surfertas Do you think you can help me add chainer in https://github.com/hunkim/DeepLearningZeroToAll? Feel free to create chainer directory and try to sync TF labs.

I really appreciate it.

**Comment by surfertas** [comment]
Hi, yes I think that is a great idea. Let me finish up to LSTM in the current project, and work to port over and modify to fit your style guide.

**Comment by hunkim** [comment]
@surfertas Wonderful! Look forward to your pull requests. If you push one or two, I guess other chainer developers will help as well.

**Comment by surfertas** [comment]
Sounds good!
